# NumPy'a Giriş

**NumPy** (Numerical Python), Python programlama dilinde büyük, çok boyutlu diziler ve matrisler üzerinde çalışmak için tasarlanmış açık kaynaklı bir kütüphanedir. Bilimsel hesaplama, veri analizi ve makine öğrenimi gibi alanlarda sıklıkla kullanılır. NumPy, Python'ın yerleşik liste veri yapısına göre daha hızlı ve daha verimlidir. NumPy’ın özellikler:

- **Hız:** NumPy, C dilinde yazıldığı için Python listelerine göre çok daha hızlıdır. Özellikle büyük veri kümeleri üzerinde çalışırken bu hız farkı oldukça önemlidir.
- **Verimlilik:** NumPy, vektör ve matris işlemlerini tek bir işlemde gerçekleştirerek kodun daha okunaklı ve daha az karmaşık olmasını sağlar.
- **Geniş Fonksiyonellik:** NumPy, matematiksel ve bilimsel hesaplamalar için çok çeşitli fonksiyonlar sunar. Bu fonksiyonlar sayesinde karmaşık işlemleri birkaç satır kodla gerçekleştirebilirsiniz.

### **NumPy'ın Temel Kavramları**

- **ndarray (N-boyutlu dizi):** NumPy'ın temel veri yapısıdır. Birden fazla boyutlu sayısal verileri tutmak için kullanılır.
- **Shape:** Bir dizinin boyutlarını belirten bir tuple'dır. Örneğin, (3, 4) şeklindeki bir dizi 3 satır ve 4 sütundan oluşur.
- **Dtype:** Dizideki elemanların veri tipini belirtir (int, float, bool vb.).

### Numpy Kurulumu

Bilgisayara kurulumu yaptıktan sonra son sürüm için yapılması gereken, terminale pip install numpy yazmak.

### **NumPy İçe Aktarım**

In [2]:
import numpy as np # type: ignore

In [3]:
# Bir boyutlu dizi
a = np.array([1, 2, 3, 4, 5])
# İki boyutlu dizi, Bunun elemanları yani bir vektör. Yukarıda skalardı burada vektörlerden oluşuyor dizi.
b = np.array([[1, 2, 3], [4, 5, 6]])
# Sıfırlardan oluşan 3x3'lük bir dizi. 
c = np.zeros((3, 3))
print (c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### **NumPy Dizileri Üzerinde İşlemler**

NumPy dizileri üzerinde aritmetik işlemler, indeksleme, kesme ve daha birçok işlem yapılabilir.

In [4]:
# Toplama
# result = a + b
# Çarpma
result = a * 2
print (result)
# Elemana erişim
value = a[2]
print (value)
# Kesme
subarray = a[1:4]
print (subarray)

[ 2  4  6  8 10]
3
[2 3 4]


### **NumPy Fonksiyonları**

NumPy, matematiksel ve istatistiksel işlemler için çok sayıda fonksiyon sunar.

- **mean():** Dizinin ortalamasını hesaplar.
- **std():** Dizinin standart sapmasını hesaplar.
- **sum():** Dizinin tüm elemanlarının toplamını hesaplar.
- **min():** Dizinin en küçük değerini bulur.
- **max():** Dizinin en büyük değerini bulur.

In [8]:
# Ortalama
mean_value = np.mean(a)
print (mean_value)
# Standart sapma
std_value = np.std(a)
print (std_value)

3.0
1.4142135623730951


### Python vs NumPy Örnek

İki listedeki karşılıklı elemanların çarpımlarını alarak yeni bir liste yapalım. Asimetrik vektörel (tek boyutlu) listelerle işlem yapılmaz. Gerekirse sonlarına 0 konarak eşitlenirler.

In [3]:
x = [4, 8, 2, 3, 8, 1, 3, 6, 3, 8, 7, 3, 7, 3, 5, 9, 3, 4, 3, 8, 2, 5]
y = [5, 7, 2, 4, 2, 5, 7, 2, 4, 4, 3, 1, 5, 6, 2, 5, 3, 7, 3, 8, 1, 6]
xy = [] #xy adında boş bir liste oluşturuluyor. Bu liste, çarpım sonuçlarını tutacak.
for i in range(0, len(x)): # Burada direkt olarak listenin içini döngüye sokmuyor aslında, liste içindeki eleman sayısı kadar listeyi döngüye sokuyor.
# Bu nedenle i aşağıda 0'dan başlayan bir rakam olarak kullanılıyor
	xy.append(x[i]*y[i]) #  Bu satır, x listesinin i'inci elemanını alır, y listesinin i'inci elemanını alır, çarpar ve sonucu xy listesinin sonuna ekler.
	
print (xy)

[20, 56, 4, 12, 16, 5, 21, 12, 12, 32, 21, 3, 35, 18, 10, 45, 9, 28, 9, 64, 2, 30]


Bunun yerine NumPy kullansaydık

In [5]:
x = np.array(x)
y = np.array(y)
print (x*y)

[20 56  4 12 16  5 21 12 12 32 21  3 35 18 10 45  9 28  9 64  2 30]
