### **NumPy Dizinleri Oluşturma**

- **np.array():** Mevcut bir Python listesinden veya tuple'dan bir NumPy dizisi oluşturur. Parantez içine genelde bir liste verilir.
- **np.arange():** Belirtilen aralıkta eşit aralıklı değerlerden oluşan bir dizi oluşturur.
- **np.zeros():** Belirtilen şekle sahip, tüm elemanları sıfır olan bir dizi oluşturur. Örneğin bir yapay sinir ağında padding vs kullanılacağında, 0'lardan oluşan bir matris veya vektöre ihtiyacımız oluyor.
- **np.ones():** Belirtilen şekle sahip, tüm elemanları bir olan bir dizi oluşturur.
- **np.random.rand():** Belirtilen şekle sahip, 0 ile 1 arasında rastgele sayılardan oluşan bir dizi oluşturur.

#### Temelde Bu

In [2]:
import numpy as np

Dizinlerin (Array) boyutları vardır. Boyutsuz diyebileceğimiz scalar dizeler de vardır.

In [6]:
# Scalar dizin
arr = np.array(42)
# 1 Boyutlu dizeler
arr1 = np.array([1, 2, 3, 4, 5])
# 2 boyutlu dizeler
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
# 3 Boyutlu dizeler
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)
# Dizinin boyutunu öğrenmek için
print(arr.ndim)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
3


An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [27]:
# Bir boyutlu dizi
a = np.array([1, 2, 3, 4, 5])
# İki boyutlu dizi, Bunun elemanları yani bir vektör. Yukarıda skalardı burada vektörlerden oluşuyor dizi.
b = np.array([[1, 2, 3], [4, 5, 6]])
# Sıfırlardan oluşan 3x3'lük bir dizi. 
c = np.zeros((3, 3))
print (c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
blob = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
blob

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [ ]:
z = np.arange(10, 16)
z

array([10, 11, 12, 13, 14, 15])

In [28]:
np.zeros(6) # Tek boyutlu tüm elemanları 0 olan bize dizi oluşturur.
np.ones(2) # tüm elemanları 1 olan bir dizi oluşturur.

array([1., 1.])

In [48]:
y = np.ones((3, 3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.full((4,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [30]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [31]:
b = np.arange(3,10)
b

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
c = np.arange(0,12, 2)
c

array([ 0,  2,  4,  6,  8, 10])

In [33]:
np.arange(0,6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [34]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

np.linspace(başlangıç, bitiş, sayı): Bu fonksiyon, belirtilen başlangıç ve bitiş değerleri arasında eşit aralıklı olarak "sayı" adet sayıdan oluşan bir dizi oluşturur. 

In [35]:
np.linspace(0,10,5)
#  0 ile 10 arasında eşit aralıklarla 5 adet sayıdan oluşan bir dizi

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Random Dizinler Oluşturma

In [36]:
np.random.random(3)

array([0.70878498, 0.2612281 , 0.3447056 ])

In [37]:
np.random.random((4,3))

array([[0.69176773, 0.90617085, 0.73334746],
       [0.34029807, 0.34891179, 0.42214826],
       [0.27973542, 0.45488773, 0.90532595],
       [0.16729162, 0.6260813 , 0.64955786]])

In [38]:
np.random.randint(0,20, 4)

array([16, 19, 10,  1])

In [39]:
np.random.randint(0,20, (4,4)) 
# Oluşturulacak dizinin boyutunu belirtiyor.  4 satır, 4 sütundan oluşan toplam 16 elemanlı bir matris

array([[ 7, 12,  8, 15],
       [ 8,  3, 15, 19],
       [ 6,  8,  8,  1],
       [13,  8, 15,  9]])

### NumPy Dizin İşlemleri

In [40]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [41]:
x = a + 8
x

array([ 8,  9, 10, 11])

In [42]:
c = a * 2
c

array([0, 2, 4, 6])

In [43]:
a + c

array([0, 3, 6, 9])

np.sin() NumPy kütüphanesindeki trigonometrik fonksiyonlardan biridir, verilen bir açının sinüsünü hesaplar. Aldığı argüman verilen açıyı temsil eder. Açılar genellikle radyan cinsinden ifade edilir.

In [44]:
a * np.sin(c) #c açısının sinüsünü alıp, sonucu a ile çarpar

array([ 0.        ,  0.90929743, -1.51360499, -0.83824649])

In [46]:
a * np.sqrt(c)

array([0.        , 1.41421356, 4.        , 7.34846923])

In [50]:
f = np.arange(0, 9).reshape(3, 3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
g = np.ones((3,3))
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Matris çarpımı, biraz karmaşık bir işlemdir; basitçe f matrisinin her satırı ile g matrisinin her sütunu çarpılır ve sonuçlar yeni bir matriste toplanır. Bu işlem için belirli kurallar vardır. Aşağıdaki örnekte yeni matrisin ilk elemanı, f matrisinin ilk satırı (0, 1, 2) ile g matrisinin ilk sütunu (1, 1, 1) çarpılarak elde edilir: (01) + (11) + (2*1) = 3.

In [54]:
np.dot(f,g)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [56]:
blob

array([3.3, 4.5, 1.2, 5.7, 0.3])

#### Kendi İçinde İşlemler

In [58]:
blob.sum()

15.0

In [59]:
blob.min()

0.3

In [60]:
blob.max()

5.7

In [61]:
blob.std() # Standart Sapma

2.0079840636817816

In [63]:
blob.mean()

3.0

### Indeks İşlemleri

In [65]:
z[4]

14

In [66]:
z[-1]

15

In [67]:
z[[1,3,4]]

array([11, 13, 14])