# NumPy Fonksiyonlar

### ndim, shape ve size
- **ndim:** Bir dizinin kaç boyutlu olduğunu belirtir. Sıradan bir liste tek boyutlu olduğu için ndim değeri 1'dir. Matrisler ise iki boyutlu olduğu için ndim değeri 2 olur.
- **shape:** Bir dizinin her bir boyutunun uzunluğunu gösteren bir tuple'dır. Örneğin, shape değeri (3, 4) olan bir dizi 3 satır ve 4 sütundan oluşur.
- **size:** Dizideki toplam eleman sayısını verir. Yani shape tuple'ındaki tüm değerlerin çarpımına eşittir.

In [1]:
import numpy as np

# Tek boyutlu bir dizi
a = np.array([1, 2, 3, 4])
print("a.ndim:", a.ndim)  # Çıktı: 1
print("a.shape:", a.shape)  # Çıktı: (4,)
print("a.size:", a.size)   # Çıktı: 4

# İki boyutlu bir dizi (matris)
b = np.array([[1, 2, 3], [4, 5, 6]])
print("b.ndim:", b.ndim)  # Çıktı: 2
print("b.shape:", b.shape)  # Çıktı: (2, 3)
print("b.size:", b.size)   # Çıktı: 6

# Üç boyutlu bir dizi (tensor)
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("c.ndim:", c.ndim)  # Çıktı: 3
print("c.shape:", c.shape)  # Çıktı: (2, 2, 2)
print("c.size:", c.size)   # Çıktı: 8

a.ndim: 1
a.shape: (4,)
a.size: 4
b.ndim: 2
b.shape: (2, 3)
b.size: 6
c.ndim: 3
c.shape: (2, 2, 2)
c.size: 8


### NumPy Dizisi Oluşturma Fonksiyonları

### **Daha Fazla Özellik ve İşlem**

- **dtype:** Dizideki elemanların veri tipini gösterir (int, float, bool vb.).
- **itemsize:** Her bir elemanın bellekte kapladığı bayt sayısını verir.
- **reshape():** Dizinin şeklini değiştirmek için kullanılır. Ancak toplam eleman sayısı aynı kalmalıdır.
- **resize():** Dizinin boyutunu değiştirmek için kullanılır. Yeni boyut, mevcut eleman sayısından fazlaysa ek elemanlar sıfır veya belirtilen bir değerle doldurulur. Ancak bu metod, verilen diziyi yerinde değiştirir yani yeni bir dizi oluşturmaz. Bu nedenle dönüş değeri None'dır yani herhangi bir değer döndürmez.
- **flatten():** Çok boyutlu bir diziyi tek boyutlu bir diziye dönüştürür.

In [7]:
print (a.dtype)

b_reshaped = b.reshape(3, 2)
# print (b_reshaped)

c_resized = c.resize(4, 2, 2) #Son iki eleman sıfırla doldurulur
print (c_resized) # None döndürür çünkü
# Yeni bir dizi oluşturmak ve orijinal diziyi değiştirmek istemiyorsak, 
# resize() yerine reshape() metodunu veya zeros() metodu ile yeni bir dizi oluşturup elemanları kopyalamak daha uygun olacaktır.
# reshape() kullanımı

c_resized = c.reshape(4, 2, 2)
# zeros() kullanımı
# c_resized = np.zeros((4, 2, 2))
# c_resized[:2, :, :] = c

c_flattened = c.flatten()
# print (c_flattened)

int32
None
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


Access the third element of the second array of the first array:
Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with

In [ ]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])