**1- 3x2 lik 1 lerden oluşan bir matris oluşturun**

In [2]:
import numpy as np
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


**2- 2x5 6'lardan oluşan bir matris oluşturun**

In [3]:
b = np.full((2,5),6)
print (b)

[[6 6 6 6 6]
 [6 6 6 6 6]]


**3- 2-100 arası 2 şer atlayan bir array oluşturun**

In [4]:
c = np.arange(2,100,2)
print (c)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


**4- 3-10 arasında eşit dağılımlı 50 değer oluşturan bir array oluşturun**

In [5]:
d = np.linspace(3,10,50)
print (d)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


**5- 10 boyutunda sıfırlardan oluşan bir vektör (array) oluşturun, 5. değeri 1 olsun**

In [6]:
# Doğru anladığımdan emin değilim

e = np.zeros(10)
e[4] = 1
print (e)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**6- 0 dan 8 e kadar sıralı değerler barındıran 3x3 lük bir matris oluşturun**

In [7]:
f = np.arange(0,9).reshape(3,3)
print (f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**7- Rasgele sayılardan oluşan 3x3x3 lük bir array oluşturun**

In [8]:
g = np.random.random((3,3))
print (g)

[[0.97182221 0.18732036 0.8175653 ]
 [0.93665365 0.17874912 0.28141621]
 [0.18596507 0.53565283 0.94682233]]


**8- 10x10 luk bir array oluşturun. Max ve min değerlerini bir değişkene atayın**

In [9]:
h = np.random.randint(0,100,(10,10))
print (h)
h_max = h.max()
h_min = h.min()
print (h_max)
print (h_min)

[[62 84 22 47 66 47 14 35 91 41]
 [67 91 67  1 91 50 62 24 47 39]
 [80 38 86 14 17 20  4  3  2 62]
 [47 89  3 92 81 75 25 47 64 88]
 [54 35 91 76 29 57  6 87 69 69]
 [72 34 78 47 31 13 48 51 72 12]
 [76 92 98 37 21 96 94  3 62 16]
 [23 99 10 40 96 95  7 19 64 20]
 [ 0 10 72 68 71 48 89 46 54 75]
 [ 7 79 97 27 38 86 38 34 42 91]]
99
0


**9- Birlerden oluşan 5x3 matrisi birlerden oluşan 3x2 matrisle çarpın**

In [10]:
x = np.ones((5,3))
y = np.ones((3,2))
result = x @ y

print(result)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


**10- Her bir satırı 0 1 2 3 4 arrayinden oluşan 5x5 matris oluşturun**

In [11]:
z = np.full((5, 5), np.arange(5))
print(z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**11- 10 elemanlı rastgele bir array oluşturun ve küçükten büyüğe sıralayın**

In [13]:
arr = np.random.random(10)
print (arr)
sorted_arr = np.sort(arr)
print (sorted_arr)

[0.23747455 0.51869634 0.88762883 0.00675117 0.18655914 0.05130153
 0.05591854 0.80835225 0.52720192 0.34121829]
[0.00675117 0.05130153 0.05591854 0.18655914 0.23747455 0.34121829
 0.51869634 0.52720192 0.80835225 0.88762883]
